import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '../components/Navigation';
import Footer from '@/components/Footer';
import { StateProvider } from '@/context/StateContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-[#FBF6EB] overflow-y-scroll">
      <StateProvider>
        <body className={`${inter.className} min-h-screen `}>
          <Navigation />
          {children}
          <Footer />
        </body>
      </StateProvider>
    </html>
  );
}
